### ISSUE TITLE
Create registry key for uninstaller in the Windows NSIS script

### ISSUE THREAD

**Issue by michaelrfraser** [openlvc/portico#132]
### Summary
----
Just installed the windows distribution of Portico 2.0.1 via the installer today. I noticed that the application is not listed in the "Uninstall or change a program" dialog in Windows. 

While the installer creates an uninstall executable in the installation directory, a registry key is required to have it listed in the above mentioned dialog.

I believe you can do this with NSIS by using the following directive

```
WriteRegStr HKLM "Software\Microsoft\Windows\CurrentVersion\Uninstall\${PUBLISHER} ${ABBR_NAME}" "UninstallString" "$INSTDIR\Uninstall.exe"
```

Where:
- `$(PUBLISHER)` is the publisher name the product is registered under (e.g. The Portico Project)
- `$(ABBR_NAME)` is the product name (e.g. Portico)

**Note** PUBLISHER and ABBR_NAME are probably already being used to register Start Menu shortcuts

### Acceptance Criteria
----
Once complete, I shall be able to:
 * Uninstall portico from the "Uninstall or change a program" dialog in Windows

**Comment by michaelrfraser** [comment]
PS: Also noted that the uninstaller does not delete the Start Menu items that the installer created

**Comment by michaelrfraser** [comment]
PR Submitted to https://github.com/openlvc/portico/pull/133

- Added registry entries to register the Portico uninstaller with Windows
- Ensured all Start Menu items are cleaned up on uninstall

**Comment by timpokorny** [comment]
Merged
