### ISSUE TITLE
False alarm on "Federate Disconnected / Crashed" during debug operations.

### ISSUE THREAD

**Issue by 314314314** [openlvc/portico#141]
During debug sessions, federate execution maybe unresponsive, causing the RTI to think it has crashed/ disconnected, consequently synthesizing resign messages. Increasing portico.jgroups.timeout   setting helped a little, but it also slows down sync point related actions. Please suggest a work around on this problem.

Thankyou!

**Comment by timpokorny** [comment]
G'day @314314314 - Apologies for the delay, in the midst of some non-work related emergency things.

The auto-resign is stimulated from JGroups which is what Portico uses internally for comms. Basically, each federate should be communicating with the others over a back-channel around things such as presence. If these communications are working you should never see this sort of problem. They should be happening on separate threads, so a large workload inside the federate still should not affect to this level.

Have you got any more information about how long things pause before this happens and what is going on to cause the pauses (CPU intensive workload by the federate for example?).

If I could also ask you to turn up the logging to `DEBUG` in the `RTI.rid` file and send through the log that would be fantastic and would help us identify what we can do to work around.

**Comment by 314314314** [comment]
Good day!
After revising my debug procedure, I realize the problem is caused by pausing the federate as well as the back-channel thread. I can avoid the problem by pausing only federate related thread.

Thank you!

**Comment by timpokorny** [comment]
Excellent! I am still a little concerned as the polling for fault detection should process itself in the background. If there is any information you feel comfortable sharing please do provide, otherwise I shall mark this one as closed. Cheers, Tim
