### ISSUE TITLE
IEEE1516E: LogicalTimeFactoryFactory cannot load factory for HLAinteger64Time 

### ISSUE THREAD

**Issue by DoctorRuss** [openlvc/portico#142]
In `codebase/src/java/portico/hla/rti1516e/LogicalTimeFactoryFactory.java`, the ServiceRegistry looks up the available LogicalTimeFactory implementations. These are set in `codebase/resources/jars/portico.jar/META-INF/services/hla.rti1516e.LogicalTimeFactory`. This file refers to a non-existent class `org.portico.impl.hla1516e.types.time.IntegerTimeFactory`.

### How found
In my code, I was trying to load a Factory for HLAinteger64Time. 
* LogicalTimeFactoryFactory loads the Service registry, which reads the `META-INF/services/hla.rti1516e.LogicalTimeFactory` file.
* First entry is `org.portico.impl.hla1516e.types.time.DoubleTimeFactory`; an instance is constructed and getName does not match HLAinteger64Time.
* It then tries to construct an org.portico.impl.hla1516e.types.time.IntegerTimeFactory instance. Class isn't found, exception thrown.

### Solution
Update `codebase/resources/jars/portico.jar/META-INF/services/hla.rti1516e.LogicalTimeFactory` to use `org.portico.impl.hla1516e.types.time.LongTimeFactory`.

**Comment by timpokorny** [comment]
Filed against `portico-2.1` release and asking @michaelrfraser to do a quick fix and push through the change to `master`.

**Comment by michaelrfraser** [comment]
Merged PR into maintenance-2.0.x. Closing issue.
