### ISSUE TITLE
Portico message handler loading is not working inside web applications

### ISSUE THREAD

**Issue by icemagno** [openlvc/portico#157]
Hi Tim, 
I'm (again) trying to start a Federation in a web application. I've updated my modified (working) lib to your new up-to-date one and put in my web application, but when my application is starting it freezes at RtiFactoryFactory.getRtiFactory().getRtiAmbassador() method.

I can't get any clue to what is wrong becaus I have no logging, even with RTI.rid in place.

Please, I need so much to run Portico in a web environment.

![portico_web](https://cloud.githubusercontent.com/assets/4127512/11345438/087f7aae-91fe-11e5-9e04-abded9b0ec9c.png)

[]'s

**Comment by timpokorny** [comment]
G'day mate, That is very strange. Are you certain that the RID file is getting picked up? One option is to manually put some logging of your own (System.out.println stuff) into your own Portico build and see how far it is getting?

What happens if you try to construct theRTIambassador directly by its complete classpath (`org.portico.impl.hla1516e.Rti1516eAmbassador`)?

Are you able to step into it inside Eclipse to see where it is stalling?

**Comment by icemagno** [comment]
Hi Doc.
I'll try to embed the portico's source into my web rather than use the lib.
so I'll be able to track this.
 Will put the results here ASAP.

**Comment by icemagno** [comment]
For now I can tell you the issue is in Impl1516eHelper constructor:
The execution will stop here:  this.lrc = new LRC( this );

When I try to put a log ( System.out.println ) in the LRC constructor, not is printed, leading me to think the problem is something in Tomcat class loader.

Will investigate more.

**Comment by icemagno** [comment]
After tracing, I found the problem.
As you can see, the RTI_HOME var is set ( see the picture in first post ).
But...
Tracing the flow to Container.locatePlugins() I can see Portico can't get it, reaching this line:

316: logger.warn( "Couldn't locate RTI_HOME/lib/portico.jar on system classpath, is RTI_HOME set?" );

This is because RTI_HOME points to the local file system, out of Tomcat.
So, the userPluginPath will be the Eclipse plugins folder (same name) and it will take a very long time to scan all files in this folder.

Actually, it don't freezes, but take too much time and Tomcat giveup starting procedure.

**Comment by icemagno** [comment]
Solved bypassing the ./plugins subfolder. In a normal situation this will not be a problem since this folder is owned by Eclipse. In a pure Tomcat environment I think this folder will not exists.

Added RTI_HOME "by hand" using this hack tip:
http://stackoverflow.com/questions/318239/how-do-i-set-environment-variables-from-java

to point to a folder under the web application folder (accessible for Tomcat).

Added RID file using same way ("RTI_RID_FILE"):

For now, I removed this code in Container.getContainerPluginPath() 

		File localLocation = new File( "./plugins" );
		if( localLocation.exists() && localLocation.canRead() )
			paths.add( getCanonicalFile(localLocation) );

**Comment by icemagno** [comment]
Now I'm getting this error:

hla.rti1516e.exceptions.RTIinternalError: Unknown exception received from RTI (class hla.rti1516e.exceptions.RTIinternalError) for createFederationExecution(): No response from RTI (null) for message type: CreateFederation



Caused by: hla.rti1516e.exceptions.RTIinternalError: No response from RTI (null) for message type: CreateFederation
	at org.portico.impl.hla1516e.Rti1516eAmbassador.processMessage(Rti1516eAmbassador.java:5564)
	at org.portico.impl.hla1516e.Rti1516eAmbassador.createFederationExecution(Rti1516eAmbassador.java:315)
	... 11 more

**Comment by timpokorny** [comment]
G'day mate, OK - that makes sense and is progress. Portico uses this way of auto-discovering its plugins by looking inside its JAR file :( After that it goes to look inside the plugins folder for any extensions to the core Portico message handlers.

The reason you are getting that message is because it hasn't been able to locate its own handlers, so when the "Create" message is sent, there is no handler for it.

I really need to just remove this auto-discovery mechanism. It is a measure of flexibility that we do not need. That said, it exists right now and needs to be dealt with. What happens if you copy the portico jar under the plugins folder as well? Duplicating it, but that may help it pick up its core handlers as plugins?

**Comment by icemagno** [comment]
Well, you aready have the portico JAR location by using RTI_HOME.
but I can't see where you use this information to find the JAR.
In Container.locatePlugins() you're using the Classpath class to search for portico JAR file, but the constructor of Classpath makes use of 

systemLoader = (URLClassLoader)ClassLoader.getSystemClassLoader();

I can't rely on this to find portico.jar in classpath.
In a web environment I think this is different, so I'll try to "inject" RTI_HOME/portico.jar by hand in 
originalSystemPath at Container.locatePlugins() by using System.getenv("RTI_HOME").

What do you think?

**Comment by icemagno** [comment]
The portico JAR file was found.
Container.locatePlugins() have now this piece of code to inject RTI_HOME/portico.jar by hand in originalSystemPath search list (ugly , hum? )

               ...
		this.porticoJarFile = null;
        	URL[] result = originalSystemPath;
		try {
			String rti_home = System.getenv("RTI_HOME");
			URL[] portijar = new URL[]{
				( new File( rti_home + "/portico.jar")).toURI().toURL() 
			};		
			
			int length = portijar.length + originalSystemPath.length;
			result = new URL[length];
			System.arraycopy(portijar, 0, result, 0, portijar.length);
			System.arraycopy(originalSystemPath, 0, result, portijar.length, originalSystemPath.length);
		} catch ( Exception e ) {
		}
		
		for( URL url : result )
		{
			String path = url.getPath();
                        ...


Now I'm getting this error:
![erro003](https://cloud.githubusercontent.com/assets/4127512/11421254/c09cc5f6-941a-11e5-8200-977ce119d5d7.png)

when reach this line:

![erro002](https://cloud.githubusercontent.com/assets/4127512/11421267/d3196086-941a-11e5-8b29-329d3974360d.png)

for some reason my debugger is not going to AnnotationParser.parseForAnnotation().
I can't go further. Any ideas?

**Comment by timpokorny** [comment]
OK - this is starting to get a bit complicated. What are your timelines? I could try to hack in a fix for this dynamic class loading stuff.

**Comment by icemagno** [comment]
I'm confortable. I can wait for you to work with your time. Thanks. No hurry.

I think I'm in trouble with these "plugins" inside the main JAR.
If you have basic plugins, wich is fundamental  part of the application, you could load it internally and allow to load others as separated JARS inside "plugins" folder.

The web container is captious with class loaders. I think is not a good idea loading the portico JAR twice to looking for classes you already know the names and could be loaded internally, as they are critical to run the application. 

I know you're very, very, very busy and already know all about this, but I reached a point I can't go further because my knowledges about class loaders is very limited.

**Comment by timpokorny** [comment]
I think I'll just try and remove the dynamic loading altogether and have it statically compiled into code. Will attempt to do later on tonight (0830 here).

**Comment by icemagno** [comment]
If my memory still good, you have a baby recently. No hurry man.

**Comment by icemagno** [comment]
There is something I can do to help you?

**Comment by timpokorny** [comment]
G'day mate. Sorry. I have stated on this tonight. Currently working in a static message handler registry against which all handlers must be registered to be usable. Will allow me to remove a lot of old code and to make everything explicit. Removes the dynamic load elements so that the only requirement is that the relevant classes be available on the system classpath in any form. No more classpath searching. Hopefully a lot more robust and safe to deploy inside a web app.

**Comment by icemagno** [comment]
Many thanks Doc!! You're the best. I'll try this ASAP. I almost blow my mind when trying to do a inverse way: embed a Tomcat server into a java application, so I can change the loading order ( Portico first, Tomcat last ).

**Comment by timpokorny** [comment]
That looks pretty sleek! You'll have to link it up so I can reference it from the readme (which I need to rewrite now as well!).

Fix just pushed that should _hopefully_ take care of the issue. It's on `master` now. Removed the dynamic plugin loading and puts in something entirely un-clever - so it should actually work! Let me know when you confirm and I'll close the issue or we'll move to the next bug.

**Comment by icemagno** [comment]
Perfect man!! Worked like a charm! Thanks!

**Comment by timpokorny** [comment]
*pew pew* Smashing.
