### ISSUE TITLE
Spaces, Regions & Dimensions 

### ISSUE THREAD

**Issue by icemagno** [openlvc/portico#168]
Tim, what about Spaces, Regions and Dimensions using 1516e interface?
I'm trying to do some tests but:
1) It's very, very hard to find codes to show how to work with regions and spaces.
2) My own experiences leads me to this:

WARN  [main] portico.lrc: The IEEE 1516e interface doesn't yet support getDimensionHandle()

Please, I need a list of what Portico's 1516e interface can't do. It's a second NIY I found and I'm afraid it will compromise my project.

Thanks.

**Comment by icemagno** [comment]
A look into Rti1516eAmbassador class and I found the answer:
Portico don't have none of DDM functions implememnted for Evolved version....

**Comment by timpokorny** [comment]
G'day Carlos,

Sorry mate - the documentation task is long and laborious. I've got some base information up on a temporary working site, and it does have API status information from memory. You should be able to find the docs for the 1516e RTIamb here: http://timpokorny.github.io/public/documentation/developer/apistatus/ieee1516e/java.html

For the set in general you can get to them from here: http://timpokorny.github.io/public/documentation/developer/apistatus/index.html

Just click on the labels to link through to the relevant pages.

**Comment by icemagno** [comment]
Very good!
I didn't know about this site. 
But...
... I must go ahead with my blog and have no idea how to implement and test DDM.
OpenHLA is too complex to put on the road and have to link too many 3rd party libs.
Pitch RTI ( free version ) allow me only 2 Federates and I have to learn how to use it.

Portico is my only choice: its free, easy to use and I have a good support, but now I don't know what to do. I think I must keep my blog into the basics.

PS: I still have this problem: https://github.com/openlvc/portico/issues/167
can you tell me something about it?

**Comment by JeanPhilippeLebel** [comment]
Hello Carlos,

I have a DDM demo written for IEEE1516. Shouldn't be too hard to port to
1516e. Send me a private email at jpl@ds.tools

On Sun, Feb 14, 2016 at 4:27 PM, Carlos Magno Oliveira de Abreu <
notifications@github.com> wrote:

> Very good!
> I didn't know about this site.
> But...
> ... I must go ahead with my blog and have no idea how to implement and
> test DDM.
> OpenHLA is too complex to put on the road and have to link too many 3rd
> party libs.
> Pitch RTI ( free version ) allow me only 2 Federates and I have to learn
> how to use it.
>
> Portico is my only choice: its free, easy to use and I have a good
> support, but now I don't know what to do. I think I must keep my blog into
> the basics.
>
> PS: I still have this problem: #167
> <https://github.com/openlvc/portico/issues/167>
> can you tell me something about it?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openlvc/portico/issues/168#issuecomment-183980494>.
>



-- 
-------------
Jean-Philippe Lebel, Ing. MBA
ForwardSim inc
cell: 418-931-3800

**Comment by icemagno** [comment]
Hi Jean,
it is customary in my blog I show the code and provide a small functional program.
So, my readers can run and see the results.
Without the DDM implementation in Portico I'll never know if what I am telling my readers to do is correct. I can't shot in the dark.

I'm trying OpenHLA, but it is a nightmare. I gave it away.No DDM in my blog for now.

**Comment by timpokorny** [comment]
G'day Carlos,

I'd grab JPL's code and perhaps try the 2-fed Pitch version for a demo. Implemented code as a demo will help people regardless of RTI. If I was on a different RTI I'd still use demo code to get a skeleton in place, and it should all be portable to any implementation without recompile.

Cheers,
Tim

On 15 Feb 2016, at 7:36 AM, Carlos Magno Oliveira de Abreu <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Jean,
it is customary in my blog I show the code and provide a small functional program.
So, my readers can run and see the results.
Without the DDM implementation in Portico I'll never know if what I am telling my readers to do is correct. I can't shot in the dark.

I'm trying OpenHLA, but it is a nightmare. I gave it away.No DDM in my blog for now.

—
Reply to this email directly or view it on GitHub<https://github.com/openlvc/portico/issues/168#issuecomment-184006213>.


This message and any attachments are confidential and commercial-in-confidence, and are intended solely for the use of the individual or entity to whom the message is addressed. If you are not the intended recipient or the person responsible for delivering the message to the intended recipient, be advised that you have received this message in error and that any use, dissemination, forwarding, printing or copying of this message and any file attachments is strictly prohibited. Any views or opinions presented are solely those of the author and do not necessarily represent those of Calytrix Technologies. If you have received this message in error, please immediately notify us by reply message to the sender.

**Comment by icemagno** [comment]
You're the best!
