### ISSUE TITLE
How to enable multiple isolated federation execution?

### ISSUE THREAD

**Issue by hodiapa** [openlvc/portico#170]
how does one ensure that two federations are completely isolated and don't pass messages across the federation. What parameters are needed to be set in the RID file to ensure this isolation.

**Comment by icemagno** [comment]
It is a logical concept. All messages will still passing across the LRC but federates will receive only the data it subscribed. Think its like a router with several machines connected using different IP/Mask address

**Comment by hodiapa** [comment]
What if I want to run the example-federate with the same federation names. How can I make the two federations isolated? Would that mean I need to make some changes to the JGroups settings(like the multicast address?)

**Comment by timpokorny** [comment]
@hodiapa You have two ways. Firstly, separate them by federation name. They will not exchange messages of they are in different federations.

Secondly,if you want to use the same federation name, you can edit the address/port that the networking uses. It will be sufficient to just change the port in most cases. This is in the RID under the JGroups section. Default port is 20913, so just locate that number in the RID, change it and remember to uncomment the line (it is commented out by default). That should get you what you need. Ping back to let us know!
