### ISSUE TITLE
Was the build requirements changed?

### ISSUE THREAD

**Issue by icemagno** [openlvc/portico#171]
Refer to #162.

Hi bro,
I checked out the "master" to test #162 now I can't build the code. Need other Java version, ant or something?

Thanks.
![error](https://cloud.githubusercontent.com/assets/4127512/14916324/6e9d87dc-0def-11e6-9539-3ad6a2c1245f.png)

**Comment by timpokorny** [comment]
@icemagno I do develop with 1.8.x here, but I don't think that particular piece of code should cause issues with 1.7. Can you try `./ant clean java.sandbox` just to get everything cleaned right out before rebuilding?

**Comment by icemagno** [comment]
Yeap. Same error. Seems to me its inside JGroups code... "suspected" is of type "Address" and not iterable ...

**Comment by timpokorny** [comment]
OK - I just got the same thing with `1.7.0_51`. Looking into it.

**Comment by timpokorny** [comment]
Double check for me, but should be fixed now. You hit on the exact reason. Seems 1.8 will happily accept this but 1.7 won't.

**Comment by icemagno** [comment]
Ok. I confirm it was fixed.
