### ISSUE TITLE
createHLAvariantRecord unimplemented

### ISSUE THREAD

**Issue by bergtwvd** [openlvc/portico#173]
Using Portico 2.1.0 / HLA Evolved / Java.
FOM: RPR-2.0.

When I run my federate (built againt pRTI) with the Portico RTI I get a null pointer exception on createHLAvariantRecord. Source code says it is unimplemented and returns null.

How should I code/decode spatial variants in RPR-FOM base entities with Portico ?

Code snippet, error at `SpatialVariantStruct = encoderFactory.createHLAvariantRecord(discriminator);`

	private HLAvariantRecord<HLAoctet> createSpatialVariantDecoder() {
		// WorldLocationStruct
		HLAfixedRecord WorldLocationStruct = encoderFactory.createHLAfixedRecord();
		HLAfloat64BE X = encoderFactory.createHLAfloat64BE();
		HLAfloat64BE Y = encoderFactory.createHLAfloat64BE();
		HLAfloat64BE Z = encoderFactory.createHLAfloat64BE();
		WorldLocationStruct.add(X);
		WorldLocationStruct.add(Y);
		WorldLocationStruct.add(Z);

		// isFrozen
		HLAoctet isFrozen = encoderFactory.createHLAoctet();

		// OrientationStruct
		HLAfixedRecord OrientationStruct = encoderFactory.createHLAfixedRecord();
		HLAfloat32BE Psi = encoderFactory.createHLAfloat32BE();
		HLAfloat32BE Theta = encoderFactory.createHLAfloat32BE();
		HLAfloat32BE Phi = encoderFactory.createHLAfloat32BE();
		OrientationStruct.add(Psi);
		OrientationStruct.add(Theta);
		OrientationStruct.add(Phi);

		// VelocityVectorStruct
		HLAfixedRecord VelocityVectorStruct = encoderFactory.createHLAfixedRecord();
		HLAfloat32BE XVelocity = encoderFactory.createHLAfloat32BE();
		HLAfloat32BE YVelocity = encoderFactory.createHLAfloat32BE();
		HLAfloat32BE ZVelocity = encoderFactory.createHLAfloat32BE();
		VelocityVectorStruct.add(XVelocity);
		VelocityVectorStruct.add(YVelocity);
		VelocityVectorStruct.add(ZVelocity);

		// AngularVelocityVectorStruct
		HLAfixedRecord AngularVelocityVectorStruct = encoderFactory.createHLAfixedRecord();
		HLAfloat32BE XAngularVelocity = encoderFactory.createHLAfloat32BE();
		HLAfloat32BE YAngularVelocity = encoderFactory.createHLAfloat32BE();
		HLAfloat32BE ZAngularVelocity = encoderFactory.createHLAfloat32BE();
		AngularVelocityVectorStruct.add(XAngularVelocity);
		AngularVelocityVectorStruct.add(YAngularVelocity);
		AngularVelocityVectorStruct.add(ZAngularVelocity);

		// AccelerationVectorStruct
		HLAfixedRecord AccelerationVectorStruct = encoderFactory.createHLAfixedRecord();
		HLAfloat32BE XAcceleration = encoderFactory.createHLAfloat32BE();
		HLAfloat32BE YAcceleration = encoderFactory.createHLAfloat32BE();
		HLAfloat32BE ZAcceleration = encoderFactory.createHLAfloat32BE();
		AccelerationVectorStruct.add(XAcceleration);
		AccelerationVectorStruct.add(YAcceleration);
		AccelerationVectorStruct.add(ZAcceleration);

		// SpatialOtherStruct DRM#0: None
		HLAfixedRecord SpatialOtherStruct = encoderFactory.createHLAfixedRecord();
		SpatialOtherStruct.add(WorldLocationStruct);

		// SpatialStaticStruct DRM#1: Static
		HLAfixedRecord SpatialStaticStruct = encoderFactory.createHLAfixedRecord();
		SpatialStaticStruct.add(WorldLocationStruct);
		SpatialStaticStruct.add(isFrozen);
		SpatialStaticStruct.add(OrientationStruct);

		// SpatialFPStruct DRM#2: DRM_FPW
		HLAfixedRecord SpatialFPStruct = encoderFactory.createHLAfixedRecord();
		SpatialFPStruct.add(WorldLocationStruct);
		SpatialFPStruct.add(isFrozen);
		SpatialFPStruct.add(OrientationStruct);
		SpatialFPStruct.add(VelocityVectorStruct);

		// SpatialRPStruct DRM#3: DRM_RPW
		HLAfixedRecord SpatialRPStruct = encoderFactory.createHLAfixedRecord();
		SpatialRPStruct.add(WorldLocationStruct);
		SpatialRPStruct.add(isFrozen);
		SpatialRPStruct.add(OrientationStruct);
		SpatialRPStruct.add(VelocityVectorStruct);
		SpatialRPStruct.add(AngularVelocityVectorStruct);

		// SpatialRVStruct DRM#4: DRM_RVW
		HLAfixedRecord SpatialRVStruct = encoderFactory.createHLAfixedRecord();
		SpatialRVStruct.add(WorldLocationStruct);
		SpatialRVStruct.add(isFrozen);
		SpatialRVStruct.add(OrientationStruct);
		SpatialRVStruct.add(VelocityVectorStruct);
		SpatialRVStruct.add(AccelerationVectorStruct);
		SpatialRVStruct.add(AngularVelocityVectorStruct);

		// SpatialFVStruct DRM#5: DRM_FVW
		HLAfixedRecord SpatialFVStruct = encoderFactory.createHLAfixedRecord();
		SpatialFVStruct.add(WorldLocationStruct);
		SpatialFVStruct.add(isFrozen);
		SpatialFVStruct.add(OrientationStruct);
		SpatialFVStruct.add(VelocityVectorStruct);
		SpatialFVStruct.add(AccelerationVectorStruct);

		// DRM#6: DRM_FPB, same as SpatialFPStruct
		// DRM#7: DRM_RPB, same as SpatialRPStruct
		// DRM#8: DRM_RVB, same as SpatialRVStruct
		// DRM#9: DRM_FVB, same as SpatialFVStruct
		// SpatialVariantStruct Discriminators
		HLAoctet[] Discriminator = new HLAoctet[10];
		for (int i = 0; i < Discriminator.length; i++) {
			Discriminator[i] = encoderFactory.createHLAoctet();
			Discriminator[i].setValue((byte) i);
		}

		// SpatialVariantStruct
		HLAoctet discriminator = encoderFactory.createHLAoctet();
		SpatialVariantStruct = encoderFactory.createHLAvariantRecord(discriminator);
		SpatialVariantStruct.setVariant(Discriminator[0], SpatialOtherStruct);
		SpatialVariantStruct.setVariant(Discriminator[1], SpatialStaticStruct);
		SpatialVariantStruct.setVariant(Discriminator[2], SpatialFPStruct);
		SpatialVariantStruct.setVariant(Discriminator[3], SpatialRPStruct);
		SpatialVariantStruct.setVariant(Discriminator[4], SpatialRVStruct);
		SpatialVariantStruct.setVariant(Discriminator[5], SpatialFVStruct);
		SpatialVariantStruct.setVariant(Discriminator[6], SpatialFPStruct);
		SpatialVariantStruct.setVariant(Discriminator[7], SpatialRPStruct);
		SpatialVariantStruct.setVariant(Discriminator[8], SpatialRVStruct);
		SpatialVariantStruct.setVariant(Discriminator[9], SpatialFVStruct);

		return SpatialVariantStruct;
	}

**Comment by anthonycramp** [comment]
Looks good. Although, there is still the requirement to implement hashCode and equals on any of the encoding types that can act as a discriminant for a variant record. I'd probably be inclined to close this issue and raise a new one to cover the addition of hashCode and equals.

**Comment by bergtwvd** [comment]
Closed. See #178 .
