### ISSUE TITLE
NullPointerException in ModelMerger

### ISSUE THREAD

**Issue by DoctorRuss** [openlvc/portico#181]
The IEEE1516e FOM module schema defines the objects and interactions elements to be optional, so that extension modules do not have to define blank object and interaction roots.

When reading each FOM module, the hla1516e fomparser checks whether these elements exist. If they do not, it leaves the ICMetadata and OCMetadata root elements of the ObjectModel as null.

The full FOM is built by the [ModelMerger.merge](https://github.com/openlvc/portico/blob/f1a790624ca9a109403cde090e0fdb64335b5cf6/codebase/src/java/portico/org/portico/lrc/model/ModelMerger.java#L95) method combines two ObjectModels together by adding object and interaction classes from the extension model, checking the new roots are not null. However, it does not verify that the base root is not null, leading to a NullPointerexception in [mergeObjectClass](https://github.com/openlvc/portico/blob/f1a790624ca9a109403cde090e0fdb64335b5cf6/codebase/src/java/portico/org/portico/lrc/model/ModelMerger.java#L158) or [mergeInteractionClass](https://github.com/openlvc/portico/blob/f1a790624ca9a109403cde090e0fdb64335b5cf6/codebase/src/java/portico/org/portico/lrc/model/ModelMerger.java#L270).

This is semi-related to #177 (NPE in ModelMerger) but different

**Comment by timpokorny** [comment]
PR merged. Will take additional look at the other ticket separately.

**Comment by timpokorny** [comment]
Minor formatting changes complete on `master` commit `bf7dde926`.

Thank-you very much @DoctorRuss !!

**Comment by timpokorny** [comment]
Also - I just moved the tests out of the generic "portico" suite and into the hla13/ieee1516e specific suites. No idea why I put them in the general suite in the first place. So these tests would not be run as part of {{java.test.ieee1516e}} or {{java.test.hla13}}.
