### ISSUE TITLE
Link is dead

### ISSUE THREAD

**Issue by beachwalker** [openlvc/portico#192]
https://porticoproject.org/getnotified.html results in 404 error

**Comment by timpokorny** [comment]
G'day @beachwalker -- just checked and you are indeed correct. Where did you get linked to there from?

**Comment by DoctorRuss** [comment]
Front page of the GitHub repo: line 19 of REAME.md

**Comment by timpokorny** [comment]
Now fixed. Was placeholder URL but nothing holding the place! Updated to point to main site page where there is a link to sign up to the mailing list ATM.
