### ISSUE TITLE
Building: Cannot find jdk when building (OpenJDK, Arch Linux)

### ISSUE THREAD

**Issue by stewbond** [openlvc/portico#197]
Tested building on ArchLinux with java-8-openjdk installed

```
[stew@Romulus codebase]$ ./ant
Buildfile: /home/stew/src/portico/codebase/build.xml
     [echo] Build Version: portico-2.1.0 (build 3)
 [platform] Operating System platform is: linux64

BUILD FAILED
/home/stew/src/portico/codebase/build.xml:96: The following error occurred while executing this line:
/home/stew/src/portico/codebase/profiles/linux/hla13.xml:24: Location does not contain a valid JDK [/usr/lib/jvm/java-8-oracle]

Total time: 0 seconds
```
Issue stems from:

 `^/codebase/build.properties(36): jdk.home.linux64 = /usr/lib/jvm/java-8-oracle`.  

To solve the issue, set this line to `jdk.home.linux64 = /usr/lib/jvm/default`. On Arch64 systems this is a symbolic link to `/usr/lib/jvm/java-8-openjdk` (if you've installed [jdk8-openjdk](https://www.archlinux.org/packages/extra/x86_64/jdk8-openjdk/) from official repositories) or `/usr/lib/jvm/java-8-jdk` if you've installed [java-8-oracle](https://aur.archlinux.org/packages/jdk/) from the AUR.

I wrote this bug so others could find the work-around as well.  Not too familiar with other systems so I didn't make a pull request as I didn't want to break it for anyone else.

**Comment by timpokorny** [comment]
G'day @stewbond! Thank-you very much. Uniform locations for the JDK across Linux distros is a bit of an issue. 

However, if you create a file called local.properties and put it alongside build.properties, anything in it will override the defaults (or anything from build.properties). That file is also git-ignored so it will allow you to make machine-specific changes without affecting the repo at large. 

Only problem is that you do have to make those changes on all machines you want to build on.

**Comment by timpokorny** [comment]
Did that work for you @stewbond?

**Comment by stewbond** [comment]
Yes, thanks

**Comment by geraldwinslow-lmco** [comment]
Greetings. I'm having a similar problem building Portico 2.1.3 on Red Hat 8 with Java JDK 17. I have ensured the JAVA_HOME correctly points to the JDK, added a local.properties (with overrides to point to the JDK 17 SDK) next to the build.properties file.

When I run "./ant -projecthelp", I still get the following:

$ ./ant -projecthelp
Buildfile: xxxxx/portico-portico-2.1.3/codebase/build.xml
     [echo] Build Version: portico-2.1.3 (build 0)
 [platform] Operating System platform is: linux64
[verifyJdk] Scanning for JDK {arch=amd64,ver=11}: /usr/lib/jvm/java-17-openjdk-17.0.16.0.8-2.el8.x86_64
xxxxx/portico-portico-2.1.3/codebase/build.xml:94: The following error occurred while executing this line:
xxxxx/portico-portico-2.1.3/codebase/profiles/linux/hla13.xml:24: (Verify JDK) Location not identifiable as JDK [/usr/lib/jvm/java-17-openjdk-17.0.16.0.8-2.el8.x86_64]

Curiously, in the ~/codebase/profiles/system.properties.xml file, if I move line 75 ("platform/") inside line 74 (closing comment line - "-->"), then the Java build seems to work. 

`[javac] Compiling 1112 source files`

Very strange.

Can you offer any help to get past this?  Thanks!
