### ISSUE TITLE
Infrastructure to support centralized RTI executive process

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#219]
Summary
----
Create the necessary infrastructure for a centralized RTI Server process (rtiexec) and LRC that can communicate with it. Communications between federates and the RTI (and one another) will take place over two locally separate channels:

 1. Administrative messages sent via a `control` channel, considered point-to-point (rtiexec<>federate)
 1. High volume data messages send group/broadcast messages via a `data` channel

This will help us balance performance needs for commonly used message with simplified, central control for administrative and those messages that measured by volume are less frequent in any given federation run.

It is important to note that the actual communications mechanism used to carry the messages is not prescribed. For example, the control messages can travel over a multicast channel; they do not _need_ to be point-to-point by transport, they are just that way logically.

These changes will focus on the application that will launch for the rtiexec and the infrastructure necessary to support it. We will take this chance to simplify some of the message handler association and loading semantics as well. Further, we will also complete the complimentary changes for the LRC.

The end goal is a central `rtiexec` process and a federate using an updates LRC that can establish a return PING message on both the `control` and `data` channels.

Items not part of this ticket and deferred until later:

  - RTI auto-discovery by federates
  - RID file option to allow auto-booting of an RTI process inside that of an LRC if there is no RTI found on the networok
     - This will be done mostly to mimic the current "serverless" startup of the fully-descentralized RTI
  - Any HLA standard interface messaging support

Acceptance Criteria
----
Once complete:
**User Level**
- [x] New `rtiexec` process established as RTI Server
- [x] LRC framework updated to support this and able to exchange a PING message with rtiexec on `RTIambassador::connect()` call

**Detailed**
- [x] New message loading infrastructure will replace the dynamic, annotation-driven system currently used to simplify debugging
- [x] New communications binding interface created that will support `control` and `data` logical channels 
- [x] RTIexec process able to support incoming communications via TCP unicast
- [x] RTIexec process able to support incoming communications via Multicast
- [x] LRC framework update to support control/data channel communications and new binding interface
- [x] JGroups binding implementation update
- [x] JVM binding implementation update

**Comment by bharat77s** [comment]
is it advisable for connecting more than 26 client PC on window server OS while using Portico RTI or home edition of window OS will be able to handle the federate response from clients of morethan 26 clients PC in a local lan at present

**Comment by bharat77s** [comment]
thankx for the reply,  as presently my fedarates are crashing as we increase the number of PC from 24 also the FPS is drastically reduced to 18.. we are following the star topology for connecting the CLients with the controller(Fedarate- where all packets are getting broadcasted to clients), hence thought might be all my PCs including the COntroller is runnig on WIndows 7 service PAck-1, that is why the issue. So thoguht of changing the controller PC to WIndow Server edition for scalability and renderring of the simulator

**Comment by timpokorny** [comment]
Could you perhaps explain a little more of the setup? If you could let me know any crash stuff as well we might be able to help (I'd open that as a separate ticket).

**Comment by timpokorny** [comment]
Work on this _specific_ issue is complete and it is in the branch mentioned above. Still holding that open to aggregate other disruptive work.
