### ISSUE TITLE
MOM support for request/report object instances that can be deleted

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#232]
Summary
----
Add support for the following calls MOM request/report interactions:

 - Request: `HLArequestObjectInstancesThatCanBeDeleted`
 - Report:  `HLAreportObjectInstancesThatCanBeDeleted `

Acceptance Criteria
----
Once complete, Portico shall:

- [ ] be able to confirm this functionality through the existing unit test suites

**Comment by michaelrfraser** [comment]
PR submitted to #272, placing ticket in Review

**Comment by timpokorny** [comment]
Merged in PR #272
