### ISSUE TITLE
MOM support for request/report synchronization point status

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#238]
Summary
----
Add support for the following calls MOM request/report interactions:

- Request: `HLArequestSynchronizationPoints`
- Report:  `HLAreportSynchronizationPoints`
- Request: `HLArequestSynchronizationPointStatus`
- Report:  `HLAreportSynchronizationPointStatus`

Acceptance Criteria
----
Once complete, Portico shall:

- [ ] be able to confirm this functionality through the existing unit test suites

**Comment by michaelrfraser** [comment]
Looking into this now

**Comment by michaelrfraser** [comment]
Work for this task has been completed. A PR has been submitted at #270 

This task involved creating a framework for the processing of MOM request interactions. All SendInteraction message that the RTI hears about are forwarded to the MomSendInteractionHandler which inspects the handle of the interaction and passes it onto a relevant processor.

Decoding of request parameter values is taken care of by the framework. The handler then compiles response parameters, and then asks the framework to encode them and send the response.

If an exception is raised during the processing of the request (e.g. missing parameters, invalid parameters) the processor raises a MomException which the framework reports back to the Federate through the HLAreportMOMexception interaction.

Using this framework I've implemented the following request/response interaction pairs

HLArequestSynchronizationPoints/HLAreportSynchronizationPoints
HLArequestSynchronizationPointStatus/HLAreportSynchronizationPointStatus

**Comment by timpokorny** [comment]
PR Merged. Ticket Complete.
