### ISSUE TITLE
Update cpp ieee1516e example

### ISSUE THREAD

**Issue by bShibby** [openlvc/portico#247]
*Task*
*Summary*
Update the ieee1516e example to use the new CPPinterfaces.
 
*Branches to Fix*
Master 

*Acceptance Criteria*
Once complete, I shall be able to:
 - Use the new interface classes
 - Use the restaurant XML example
 - More closely match the 1eee1516e java example

**Comment by michaelrfraser** [comment]
PR was submitted to https://github.com/openlvc/portico/pull/249 and approved.

Merged into master.
