### ISSUE TITLE
RTI side message handlers don't check if the requesting Federate is an execution member

### ISSUE THREAD

**Issue by michaelrfraser** [openlvc/portico#276]
Just noticed that if I force resign a federate from the new RTI console, the corresponding Federate code throws an NPE on the next RTIamb call it tries to make.

All federate-related calls should check whether the requesting federate is an execution member, and if not throw a `FederateNotExecutionMember`

**Comment by michaelrfraser** [comment]
PR submitted to fix this issue in #278 

Added check in RtiInbox to prevent messages being passed to a Federation if the source Federate is not a member of that federation.

**Comment by michaelrfraser** [comment]
Basic usage manual for the CLI can be found here: https://docs.google.com/document/d/1J9vTPrNERkBj7eu8DRNiKip1h77oIQusunvtxAFhBzE/edit?usp=sharing

**Comment by timpokorny** [comment]
Merged.
