### ISSUE TITLE
Federate member timeStatus is never updated

### ISSUE THREAD

**Issue by michaelrfraser** [openlvc/portico#277]
In the Portico's new centralized RTI implementation, each Federate has a member called `timeStatus`.

This member is never updated by the time functions, which instead go through the Federation's `timeManager` object.

There are several read-references to `Federate.timeStatus` (made via `Federate.getTimeStatus`) that will be getting an incorrect picture of the federate's actual time status. All references of `Federate.timeStatus` should be removed, and instead consumers should use `Federation.getTimeManager().getTimeStatus()`

**Comment by timpokorny** [comment]
Merged.
