### ISSUE TITLE
Request for a new binary release of Portico

### ISSUE THREAD

**Issue by harlan3** [openlvc/portico#289]
The current downloadable version of Portico was built on Ubuntu 14.04.6 LTS using gcc 4.8.4.  This version of Ubuntu has reached the end of standard support this month (April 2019).  A new build of Portico built on a modern linux distro is desired.  It would also be nice to have some guidance in a readme capturing the process of building Portico from source.

**Comment by michaelrfraser** [comment]
Hi there Harlan3,

I've just submitted a PR for the issue https://github.com/openlvc/portico/issues/290 which was preventing portico from being used on modern linux distributions (anything that uses gcc5 onwards).

Creating a distribution of portico from source is a fairly straightforward process if you have java installed. Simply navigate to the `codebase/` directory of the repository on the command line and run the command:

```
./ant sandbox
```

This will generate a "sandboxed" version of the distribution to the `codebase/dist` directory. If you'd like an installer simple run the following command instead:

```
./ant installer
```

Hope that information helps!

Michael

**Comment by icemagno** [comment]
Hi Michael,  have you a full step by step compile with requirements? I know I will need Java, gcc, ant , etc but I need to know all stuff and it versions.  Thanks.

**Comment by michaelrfraser** [comment]
Hey there @icemagno,

Ant is included in the repository, so you should only need gcc and java installed.

Expected versions are:

gcc 5.0
java 8.0

Please see the file `codebase/build.properties` for the default locations that the build system expects java to reside at. If they are different on your machine, simply create a copy of `build.properties` called `local.properties` and override the values to the correct path.

From there, it should just be a matter of navigating to the `codebase` directory and running either `./ant sandbox` or `./ant installer`.

Best Regards,

Michael

**Comment by icemagno** [comment]
Hi Michael, thanks for the light-speed-reply. Almost before my post.

I will try to create a Docker image with Portico. I hope I can create a kind of RTI server to act as a Federation hub.

**Comment by icemagno** [comment]
Why are you using `codebase/build.properties` to find Java and not my `JAVA_HOME` ?
Editing files is not very nice in a Docker build process.

**Comment by icemagno** [comment]
Just for register you can download a fresh version of a dockerized version of Portico in https://hub.docker.com/r/projetoarcanjo/portico
