### ISSUE TITLE
New JAR release

### ISSUE THREAD

**Issue by bergtwvd** [openlvc/portico#294]
Any chance of providing a new JAR release? Am still using one from a few years back, and I like to get up to date.

FYI: to be used in https://github.com/IVCTool.

**Comment by michaelrfraser** [comment]
Hey there @bergtwvd, can you email your address to me: michael.fraser@calytrix.com. I'll send you a dropbox link to v2.1.0. If you can also let me know what OS and bitness you want compiled that would be appreciated.

If you want to create an distribution of portico from source yourself, its a fairly straightforward process if you have java installed. Simply navigate to the codebase/ directory of the repository on the command line and run the command:

./ant sandbox
This will generate a "sandboxed" version of the distribution to the codebase/dist directory. If you'd like an installer simple run the following command instead:

./ant installer
Hope that information helps!

**Comment by bergtwvd** [comment]
That would be great. Why not creating a release under the code section in this project?

I am running on Linux, 64b. Java.

**Comment by michaelrfraser** [comment]
@bergtwvd I don't have authority to create an official release for the project as far as I'm aware, and this won't be an "official" release per-se. I have it ready to go, so if you can email me on the address above, I'll get you the dropbox link to it.

**Comment by michaelrfraser** [comment]
Built Linux 64-bit Portico 2.2.0 pre-release and delivered to @bergtwvd via email link.

**Comment by bergtwvd** [comment]
When I use 2.2.0 pre-release I get the following stacktrace:

````
master_1  | Exception in thread "main" hla.rti1516e.exceptions.ConnectionFailed: Could not find RTI running anywhere
master_1  |     at org.portico.impl.hla1516e.Impl1516eHelper.connect(Impl1516eHelper.java:166)
master_1  |     at org.portico.impl.hla1516e.Impl1516eHelper.connect(Impl1516eHelper.java:115)
master_1  |     at org.portico.impl.hla1516e.Rti1516eAmbassador.connect(Rti1516eAmbassador.java:207)
master_1  |     at federate.Federate.connect(Federate.java:57)
master_1  |     at federate.Main.main(Main.java:108)
master_1  | Caused by: org.portico.lrc.compat.JConnectionFailed: Could not find RTI running anywhere
master_1  |     at org.portico2.lrc.LRCConnection.connect(LRCConnection.java:71)
master_1  |     at org.portico2.lrc.LRC.connect(LRC.java:185)
master_1  |     at org.portico.impl.hla1516e.Impl1516eHelper.connect(Impl1516eHelper.java:162)
master_1  |     ... 4 more
master_1  | Handler: Received shutdown signal
master_1  | Handler: Wait for federate to finish
master_1  | Handler: Exit
````
