### ISSUE TITLE
Build installer error in TAR

### ISSUE THREAD

**Issue by icemagno** [openlvc/portico#297]
After do a `./ant sandbox` with success I try to do a `./ant installer` but I'm stuck in this error:

```
installer.installer:
[verifyJdk] Verified JDK (amd64): /usr/lib/jvm/java-1.8-openjdk
     [echo] Creating tarball: /home/portico/dist/portico-2.2.0-linux64.tar.gz
     [exec] tar: unrecognized option: transform=s,jre,portico-2.2.0/jre,g
     [exec] BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.
     [exec]
     [exec] Usage: tar c|x|t [-ZzJjahmvokO] [-f TARFILE] [-C DIR] [-T FILE] [-X FILE] [--exclude PATTERN]... [FILE]...
     [exec]
     [exec] Create, extract, or list files from a tar file

```

what I'm doing wrong?

**Comment by michaelrfraser** [comment]
@icemagno what linux distribution are you using? Looks like it has a version of tar that doesn't support inline file renaming.

**Comment by icemagno** [comment]
This is a Docker image with alpine linux. Can't remember the version. 

But... can I just use the SandBox instead the installer?

**Comment by icemagno** [comment]
Nevermind... changed the base image to a full Ubuntu. Will close this ticket.
