### ISSUE TITLE
There is no "portico.wan.enabled" in RTI.rid

### ISSUE THREAD

**Issue by icemagno** [openlvc/portico#306]
According with this http://timpokorny.github.io/public/documentation/user/wan.html I must set `portico.wan.enabled` to `true` if I want to connect to a "WANROUTER".

But the current [RTD.rid](https://github.com/openlvc/portico/blob/master/codebase/resources/dist/common/RTI.rid) have nothing related to WAN.

I can find this option in [this file](https://github.com/usnistgov/ucef-wrappers/blob/master/database/RTI.rid) wich is 9 months old.

Please, what is the current method to connect to a WAN router?

**Comment by timpokorny** [comment]
To use as documented you'll have to drop off the master branch and back to maintenance-2.0.x

**Comment by icemagno** [comment]
Thanks
