### ISSUE TITLE
Query: store/restore functionality

### ISSUE THREAD

**Issue by yogeshVU** [openlvc/portico#311]
How to use the store/restore functionality in portico? We would like to implement checkpointing of all the federates of the federation(currently running in Docker), and would also like to restore if any federate crashes. Any examples/pointers that will help in developing above solutions in portico?

**Comment by timpokorny** [comment]
Hi @yogeshVU,

We haven't got any specific documentation on best practiceses or approaches for using the HLA services. The closest we'd have is some of the unit tests which might help in understanding the workflow. 

You can find them here: https://github.com/openlvc/portico/tree/maintenance-2.0.x/codebase/src/java/test/hlaunit/hla13/saverestore

Also - just note that Save/Restore is only exposed in the HLA v1.3 interface at the moment.
