### ISSUE TITLE
Calling tick(5.0,5.0) equiv does not always tick for at least 5 seconds

### ISSUE THREAD

**Issue by timpokorny** [openlvc/portico#53]
Summary
--------------
While building the WAN test federate I have noticed some strange behaviour in the implementation of `tick()` (or `evokeXxx()` in 1516/e).

Calling the equivalent of `tick(5.0,5.0)` does not appear to put a federate into ticking mode for at least 5 seconds _if_ there is at least one event in the queue to be processed. It appears to process that message and then immediately return.

_Test case needed_

I have not cross-checked this against `hla13` yet to see if the same behaviour exists there. I suspect it is in the core, and so the interface will make little difference, but some of the tick semantics is implemented in the impl-helper, so it could well be that it is interface specific.

Environment and Logs
--------------------------------
 - Portico v2.0.1
 - Ubuntu 1404x64
 - WAN Test Federate
 
Reproduction Steps
-----------------------------
 - With two test federates, go through the usual pub/sub process
 - In Federate A, send an update to Federate B
 - In Federate B, call `tick(5.0,5.0)` and notice that it does not pause for the minimum tick time of 5 seconds.

Acceptance Criteria
----------------------------
Once complete I shall be able to:

  - [ ] Specify a RID setting that tells the RTI to ignore the minimum wait time and just tick until the queue is drained, returning right away if it is empty. Off by default.

**Comment by anthonycramp** [comment]
Suggestion: add RID configuration option to override this wait for minimum time and return as soon as delivering available callbacks is complete. Pitch has such an option.

I also came across this in my performance testing. I'm not sure what is correct behaviour according to the standard. Standard seems ambiguous, but intent would seem to be to wait for the minimum time.

**Comment by timpokorny** [comment]
@anthonycramp I think I may have fixed the root issue in a recent update to `master`: 169572825976841c63549074d0113c2c7b28fe83

Basically, it will now tick for at least `mintime`, after which it will tick until it either drains the queue, or reaches `maxtime`.

Adding a flag also sounds like a good option, so I'll update this ticket to focus on that.

**Comment by timpokorny** [comment]
This appears to be fixed from what I can tell.
