### ISSUE TITLE
Erroneous reporting of federate restore not supported in ieee1516e implementation

### ISSUE THREAD

**Issue by anthonycramp** [openlvc/portico#76]
#70 will override this.

The featureNotSupported notifications in the restore service methods in org.portico.impl.hla1516e.Rti1516eAmbassador all report "queryFederationSaveStatus()" instead of the actual method names.

**Comment by timpokorny** [comment]
Poo! `Ctrl-C`...`Ctrl-V` fail.

**Comment by anthonycramp** [comment]
Hehe, that's what I figured.
